execute pathogen#infect()
syntax on
filetype plugin indent on
syntax enable

if ($ITERM_PROFILE == 'solarized-dark')
    set background=dark
    colorscheme solarized
elseif ($ITERM_PROFILE == 'solarized-light')
    set background=light
    colorscheme solarized
else
    colorscheme desert
endif

set pastetoggle=<F10>
