---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/tpope/vim-pathogen.git
    dest: /Users/{{ ansible_user_id }}/.vim
  - role: osxc.repository
    clone_url: https://github.com/tpope/vim-sensible.git
    dest: /Users/{{ ansible_user_id }}/.vim/bundle/vim-sensible
  - role: osxc.repository
    clone_url: https://github.com/altercation/vim-colors-solarized.git
    dest: /Users/{{ ansible_user_id }}/.vim/bundle/vim-colors-solarized
  post_tasks:
  - copy: src=dotfiles/vimrc dest=/Users/{{ ansible_user_id }}/.vimrc backup=yes

- hosts: all
  roles:
  - osxc.common-env
