---
- name: create the common_env
  file: dest=/Users/{{ item }}/.common_env
        state=touch
        owner={{ item }}
        mode=0544
  with_items: "{{affected_users}}"

- name: create dotfiles if missing
  file: dest=/Users/{{ item[0] }}/{{ item[1] }}
        state=touch
        owner={{ item[0] }}
        mode=0544
  with_nested:
  - "{{ affected_users }}"
  - [ '.bash_profile', '.bash_login']

- name: source this common env from every known dotfile
  ignore_errors: True
  lineinfile: dest=/Users/{{ item[0] }}/{{ item[1] }}
              regexp='source ~/\.common_env'
              line='source ~/.common_env'
              owner={{ item[0] }}
              mode=0544
  with_nested:
  - "{{ affected_users }}"
  - [ '.bash_profile', '.bash_login']
